version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
